# Generated by Django 3.2.9 on 2021-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=2000)),
                ('course_isactive', models.CharField(default='True', max_length=20)),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('course_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
