# Generated by Django 3.2.9 on 2021-12-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211207_0456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='followers',
            new_name='follower',
        ),
    ]
