# Generated by Django 4.0 on 2021-12-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_applyforcourse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('message_body', models.CharField(max_length=1000)),
                ('message_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
