# Generated by Django 4.0 on 2021-12-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chatroom'),
        ),
    ]
