# Generated by Django 4.0.1 on 2022-08-31 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_chatroom_rename_receiver_message_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-message_created']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
